-- Visualizer builder script (linear)

-- Modify if necessary
local config = {
	FFT_SIZE = 1024,
	FFT_ATTACK = 20,
	FFT_DECAY = 175,
	FFT_OVERLAP = true,
	SENSITIVITY = 37.5,
	BANDS = 48,
	BAND_BAR_SIZE = 8,
	BAND_BAR_LENGTH = 400,
	BAND_BAR_MARGIN = 10, -- One side
	BAND_COLOR = "0,0,0,127"
}

-- Stop editing below this line
config.FFT_OVERLAP_SIZE = config.FFT_OVERLAP and math.floor(config.FFT_SIZE / 2) or 0

local visIni = [[
; Automatically generated by makevis.lua script.
[Rainmeter]
Update=15
BackgroundMode=1
SkinHeight=${BAND_BAR_LENGTH}

[Metadata]
Name=LinearVisualizer
Author=MikuAuahDark
Information=Visualizer, linear this time. | This skin is generated by makevis.lua script!
Version=1.0
;License=zLib license (skin generator code)

[VisAudioLevelBase]
Measure=Plugin
Plugin=AudioLevel
FFTSize=${FFT_SIZE}
FFTAttack=${FFT_ATTACK}
FFTDecay=${FFT_DECAY}
FFTOverlap=${FFT_OVERLAP_SIZE}
Sensitivity=${SENSITIVITY}
Bands=${BANDS}
]]

-- ## indicates current loop number(`i`)
local visIniBandCreateTemplate = [[
[VisBand##]
Measure=Plugin
Plugin=AudioLevel
Parent=VisAudioLevelBase
Type=Band
BandIdx=##

[VisBand##Meter]
Meter=Bar
MeasureName=VisBand##
AntiAlias=1
BarColor=${BAND_COLOR}
SolidColor=0,0,0,0
BarOrientation=Vertical
Flip=0
X=#X
Y=0
W=${BAND_BAR_SIZE}
H=${BAND_BAR_LENGTH}
]]

local function configReplace(name)
	return config[name]
end

-- Calculate the max skin dimensions.
local skinString = {
	(visIni:gsub("%${([A-Z_]+)}", configReplace):gsub("\r\n", "\n"))
}

-- Create band measure & bar meter
for i = 0, config.BANDS - 1 do
	local meterString = visIniBandCreateTemplate
		:gsub("\r\n", "\n")
		:gsub("##", i)
		:gsub("%${([A-Z_]+)}", configReplace)
		:gsub("#C", config.BAND_COLOR)
		:gsub("#X", i * (config.BAND_BAR_MARGIN + config.BAND_BAR_SIZE))
	skinString[#skinString + 1] = meterString
end

-- Write skin file.
local f = io.open("vis.ini", "w")
f:write(table.concat(skinString, "\n"))
f:close()
